[exports.common]
GPG_TTY = "$TTY"
INPUTRC = "${XDG_CONFIG_HOME}/readline/inputrc"
LESSHISTFILE = "${XDG_CACHE_HOME}/less/history"
OPENSPEC_TELEMETRY = "0"
TERMINFO = "${XDG_DATA_HOME}/terminfo"
TERMINFO_DIRS = "${XDG_DATA_HOME}/terminfo:/usr/share/terminfo"

[[exports.rules]]
id = "bash"
when_shell = "bash"
[exports.rules.values]
CLICOLOR = 1
HISTFILE = "${XDG_STATE_HOME}/bash/history"
LSCOLORS = "GxFxCxDxBxegedabagaced"

[[exports.rules]]
id = "editor-default"
[exports.rules.values]
EDITOR = "vi"

[[exports.rules]]
id = "darwin"
when_os = "darwin"
[exports.rules.values]
BASH_SILENCE_DEPRECATION_WARNING = 1

[[exports.rules]]
id = "darwin-brew"
when_os = "darwin"
when_tool = "brew"
[exports.rules.values]
HOMEBREW_NO_ANALYTICS = 1

[[exports.rules]]
id = "darwin-work"
when_os = "darwin"
when_not_personal = true
[exports.rules.values]
AWS_PROFILE = "arcus_dev"
AWS_REGION = "us-west-2"
AWS_SDK_LOAD_CONFIG = 1
TILT_NAMESPACE = "derick-rodriguez"
