[functions.flags]

[[functions.rules]]
id = "notify-darwin"
when_os = "darwin"
when_tool = "osascript"
[functions.rules.values]
notify_me = true

[[functions.rules]]
id = "work-aws-k8s"
when_os = "darwin"
when_not_personal = true
[functions.rules.values]
switchprod = true
