[onepassword.vaults]
dev = "ylehyg24v4ktnhshngeyvl4fye"
work = "ydxim6il3bd3reztx5kioejcmu"

[[onepassword.age_identities]]
item = "dx3kpkdehcae2yysw5eullpchu"
vault = "dev"

[[onepassword.age_identities]]
item = "vm3wpbooysjhhzfq2b5n3aykze"
vault = "dev"

[onepassword.items.github]
item = "pwe3o2nzdxbccxtx5uyueegqdu"
vault = "dev"

[onepassword.items.github.fields]
email = "dx7si3rrpbwq2vbg23odtjvmbu"
github_mcp_pat = "ffpafb4xoc64jwnrtqgktcjiyq"

[onepassword.items.work_domain]
item = "wuo6jezj45c2bdzyttgfvxygzu"
vault = "work"

[onepassword.items.work_domain.fields]
username = "username"
launchdarkly_reader_token_label = "launchdarkly reader token"

[onepassword.items.openai_key]
item = "d2sclj2vlu5y55x7ojx3uzm3tq"
vault = "work"

[onepassword.items.openai_key.fields]
credential = "credential"

[onepassword.items.service_account_token]
item = "pwvya36g66yls5o5zj7tcrqaci"
vault = "dev"

[onepassword.items.service_account_token.fields]
credential = "credential"

[onepassword.items.packaging_token]
item = "4itl7orehcbljin364jxdxft5e"
vault = "work"

[onepassword.items.packaging_token.fields]
username = "username"
credential = "credential"
nuget_source_url = "hostname"
npm_registry_url = "3nbmdaax4ylhygbon2ygbrbwnu"
source_key_label = "key"

[onepassword.items.wallaby]
item = "6nq62ybxd37bslycwnalaqsljy"
vault = "dev"

[onepassword.items.wallaby.fields]
license_key = "reg_code"

[onepassword.items.dropbox]
item = "vnbnqwzvzaa7xzwacfpy3raz7y"
vault = "dev"

[onepassword.items.aws_credentials]
item = "nkf7orr6g2npyzt75akxxjtfim"
vault = "work"

[onepassword.items.aws_credentials.fields]
access_key_id_label = "AWS Access Key ID"
secret_access_key_label = "AWS Secret Access Key"
arcus_dev_account_id = "ksd3ksakwq2ghhfyie6hnv7wxa"
arcus_staging_account_id_label = "arcus_staging_account_id"
arcus_prod_account_id_label = "arcus_prod_account_id"
