[shell_manifest.entries.mise-zsh]
priority = 336

[shell_manifest.entries.mise-zsh.rules]
when_tool = "mise"
when_shell = ["zsh"]

[shell_manifest.entries.mise-zsh.init.mise]
kind = "literal"
value = "eval \"$(mise activate zsh)\""
