[package_catalog.packages."visual-studio-code"]
os = "mac"
type = "common"
target_class = "all"
when_stat = "/Applications/Visual Studio Code.app"
when_tool = "code"
when_not_tool = "zed"

[shell_manifest.entries.visual-studio-code]
priority = 310

[shell_manifest.entries.visual-studio-code.rules]
when_tool = "code"

[shell_manifest.entries.visual-studio-code.exports.VISUAL]
kind = "literal"
value = "code -nw"
