[package_catalog.packages."zed"]
os = "mac"
type = "common"
target_class = "all"
brew_cask_name = "zed"
when_tool = "zed"
config_file_locations = [".config/zed"]

[shell_manifest.entries.zed]
priority = 320

[shell_manifest.entries.zed.rules]
when_tool = "zed"

[shell_manifest.entries.zed.exports.VISUAL]
kind = "literal"
value = "zed --wait"
