[package_catalog.packages."awscli"]
os = "mac"
type = "work"
target_class = "all"
brew_formula_name = "awscli"

[shell_manifest.entries.darwin-work-aws]
priority = 235

[shell_manifest.entries.darwin-work-aws.rules]
when_os = ["darwin"]
when_personal = "false"
when_tool = "aws"

[shell_manifest.entries.awscli]
priority = 234

[shell_manifest.entries.awscli.rules]
when_tool = "aws"

[shell_manifest.entries.awscli.exports.AWS_SHARED_CREDENTIALS_FILE]
kind = "literal"
value = "${XDG_CONFIG_HOME}/aws/credentials"

[shell_manifest.entries.awscli.exports.AWS_CONFIG_FILE]
kind = "literal"
value = "${XDG_CONFIG_HOME}/aws/config"

[shell_manifest.entries.awscli-work]
priority = 235

[shell_manifest.entries.awscli-work.rules]
when_tool = "aws"
when_personal = "false"

[shell_manifest.entries.awscli-work.exports.AWS_PROFILE]
kind = "literal"
value = "arcus_dev"

[shell_manifest.entries.awscli-work.exports.AWS_SDK_LOAD_CONFIG]
kind = "literal"
value = "1"

[shell_manifest.entries.darwin-work-aws.exports.AWS_REGION]
kind = "literal"
value = "us-west-2"

[shell_manifest.entries.work-aws-k8s]
priority = 247

[shell_manifest.entries.work-aws-k8s.rules]
when_os = ["darwin"]
when_personal = "false"
when_tool = "aws"

[shell_manifest.entries.work-aws-k8s.functions.switchprod]
kind = "literal"
value = """
switchprod() {
  aws eks update-kubeconfig --name=arcus-prod-aws-eksCluster-7981131 --alias=aws-arcus-prod --profile=arcus_prod
  export AWS_PROFILE=\"arcus_prod\"
  export ASPNETCORE_ENVIRONMENT=\"Production\"
}
"""

[shell_manifest.entries.work-aws-k8s.functions.switchprodsu]
kind = "literal"
value = """
switchprodsu() {
  aws eks update-kubeconfig --name=arcus-prod-aws-eksCluster-7981131 --alias=aws-arcus-prod-su --profile=arcus_prod_su
  export AWS_PROFILE=\"arcus_prod\"
  export ASPNETCORE_ENVIRONMENT=\"Production\"
}
"""
