[package_catalog.packages."bcompare"]
os = "common"
type = "common"
target_class = "all"
when_tool = "bcompare"

[shell_manifest.entries.bcompare]
priority = 255

[shell_manifest.entries.bcompare.rules]
when_os = ["linux"]
when_tool = "bcompare"

[shell_manifest.entries.bcompare.exports.DIFFPROG]
kind = "literal"
value = "bcompare"
