[package_catalog.packages."fzf"]
os = "mac"
type = "common"
target_class = "all"
brew_formula_name = "fzf"

[shell_manifest.entries.fzf]
priority = 305

[shell_manifest.entries.fzf.rules]
when_tool = "fzf"

[shell_manifest.entries.fzf.exports.FZF_DEFAULT_OPTS]
kind = "literal"
value = '''
--color=bg+:#414559,bg:#303446,spinner:#F2D5CF,hl:#E78284 \
--color=fg:#C6D0F5,header:#E78284,info:#CA9EE6,pointer:#F2D5CF \
--color=marker:#BABBF1,fg+:#C6D0F5,prompt:#CA9EE6,hl+:#E78284 \
--color=selected-bg:#51576D \
--color=border:#737994,label:#C6D0F5
'''

[shell_manifest.entries.fzf.aliases.cpf]
kind = "literal"
value = "/bin/cp -i $(fzf -i)"

[shell_manifest.entries.fzf.aliases.mvf]
kind = "literal"
value = "/bin/mv -i $(fzf -i)"

[shell_manifest.entries.fzf.aliases.rm]
kind = "literal"
value = "/bin/rm -i"

[shell_manifest.entries.fzf.aliases.rmf]
kind = "literal"
value = "/bin/.rm -i $(fzf -i)"
