[package_catalog.packages."gnupg"]
os = "common"
type = "common"
target_class = "all"
when_tool = "gpg"

[shell_manifest.entries.gnupg]
priority = 243

[shell_manifest.entries.gnupg.rules]
when_tool = "gpg"

[shell_manifest.entries.gnupg.exports.GNUPGHOME]
kind = "literal"
value = "${XDG_DATA_HOME}/gnupg"
