[package_catalog.packages."imagemagick"]
os = "mac"
type = "personal"
target_class = "all"
brew_formula_name = "imagemagick"

[shell_manifest.entries.imagemagick-functions-magick]
priority = 251

[shell_manifest.entries.imagemagick-functions-magick.rules]
when_tool = "magick"

[shell_manifest.entries.imagemagick-functions-magick.functions.fakeScan]
kind = "literal"
value = """
function fakeScan() {
  magick -density 90 ${1} -rotate 0.5 -attenuate 0.2 +noise Multiplicative -colorspace Gray scan_${1}
}
"""

[shell_manifest.entries.imagemagick-functions-convert]
priority = 252

[shell_manifest.entries.imagemagick-functions-convert.rules]
when_tool = "convert"
when_not_tool = "magick"

[shell_manifest.entries.imagemagick-functions-convert.functions.fakeScan]
kind = "literal"
value = """
function fakeScan() {
  convert -density 90 ${1} -rotate 0.5 -attenuate 0.2 +noise Multiplicative -colorspace Gray scan_${1}
}
"""
