[package_catalog.packages."nano"]
os = "common"
type = "common"
target_class = "all"
when_tool = "nano"
when_not_tool = "micro"

[shell_manifest.entries.nano]
priority = 300

[shell_manifest.entries.nano.rules]
when_tool = "nano"

[shell_manifest.entries.nano.exports.EDITOR]
kind = "literal"
value = "nano"
