[package_catalog.packages."saml2aws"]
os = "mac"
type = "work"
target_class = "all"
brew_formula_name = "saml2aws"

[shell_manifest.entries.saml2aws-functions]
priority = 253

[shell_manifest.entries.saml2aws-functions.rules]
when_tool = "saml2aws"
when_personal = "false"

[shell_manifest.entries.saml2aws-aliases]
priority = 252

[shell_manifest.entries.saml2aws-aliases.rules]
when_tool = "saml2aws"

[shell_manifest.entries.saml2aws-zsh]
priority = 251

[shell_manifest.entries.saml2aws-zsh.rules]
when_tool = "saml2aws"
when_shell = ["zsh"]

[shell_manifest.entries.saml2aws-zsh.init.saml2aws-completion]
kind = "literal"
value = "eval \"$(saml2aws --completion-script-zsh)\""

[shell_manifest.entries.saml2aws-aliases.aliases.s2a]
kind = "literal"
value = "AWS_SDK_LOAD_CONFIG=0 saml2aws"

[shell_manifest.entries.saml2aws-functions.functions.loginarcus]
kind = "literal"
value = """
loginarcus() {
  saml2aws login --browser-executable-path="/Applications/Brave Browser.app/Contents/MacOS/Brave Browser" --skip-prompt --force --profile default
}
"""

[shell_manifest.entries.saml2aws-functions.functions.loginarcussu]
kind = "literal"
value = """
loginarcussu() {
  saml2aws login --browser-executable-path="/Applications/Brave Browser.app/Contents/MacOS/Brave Browser" --skip-prompt --force -a superuser --profile default_su
}
"""

[shell_manifest.entries.saml2aws-functions.functions.logininternaltools]
kind = "literal"
value = """
logininternaltools() {
  saml2aws login --browser-executable-path="/Applications/Brave Browser.app/Contents/MacOS/Brave Browser" --skip-prompt --force -a internaltools --profile internaltools
}
"""

[shell_manifest.entries.saml2aws-functions.functions.logininternaltoolssu]
kind = "literal"
value = """
logininternaltoolssu() {
  saml2aws login --browser-executable-path="/Applications/Brave Browser.app/Contents/MacOS/Brave Browser" --skip-prompt --force -a internaltools_superuser --profile internaltools_su
}
"""

[shell_manifest.entries.saml2aws-functions.functions.loginaccelerator]
kind = "literal"
value = """
loginaccelerator() {
  saml2aws login --browser-executable-path="/Applications/Brave Browser.app/Contents/MacOS/Brave Browser" --skip-prompt --force -a accelerator --profile accelerator
}
"""

[shell_manifest.entries.saml2aws-functions.functions.loginacceleratorsu]
kind = "literal"
value = """
loginacceleratorsu() {
  saml2aws login --browser-executable-path="/Applications/Brave Browser.app/Contents/MacOS/Brave Browser" --skip-prompt --force -a accelerator_superuser --profile accelerator_su
}
"""
