[shell_manifest.entries.onepassword-agent]
priority = 225

[shell_manifest.entries.onepassword-agent.rules]
when_os = ["darwin"]
when_stat = "/Applications/1Password.app"

[shell_manifest.entries.onepassword-agent.exports.SSH_AUTH_SOCK]
kind = "literal"
value = "$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
