[package_catalog.packages."thefuck"]
os = "mac"
type = "common"
target_class = "all"
brew_formula_name = "thefuck"

[shell_manifest.entries.thefuck-init]
priority = 330

[shell_manifest.entries.thefuck-init.rules]
when_tool = "fuck"

[shell_manifest.entries.thefuck-init.init.thefuck]
kind = "literal"
value = "eval $(thefuck --alias)"
