[shell_manifest.entries.zsh-core]
priority = 180

[shell_manifest.entries.zsh-core.rules]
when_shell = ["zsh"]

[shell_manifest.entries.zsh-core.aliases.reload]
kind = "literal"
value = "source ~/.zshrc"

[shell_manifest.entries.zsh-core.aliases.clear]
kind = "literal"
value = "z4h-clear-screen-soft-bottom"

[shell_manifest.entries.zsh-core.functions.alias]
kind = "literal"
value = '''
alias() {
  if (( $# == 0 )); then
    builtin alias | LC_ALL=C sort
  else
    builtin alias "$@"
  fi
}
'''
